CREATE DATABASE usernames;
USE usernames;
CREATE TABLE info (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE info
ADD email VARCHAR(255) NOT NULL;
ALTER TABLE info
ADD password VARCHAR(255) NOT NULL;

